mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.food_mart.modules.order.domain.mapper

file:
  upload-dir: uploads/items

spring:
  application:
    name: food-mart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mart?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: spring.mart
    password: qlqjs
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'false'
        use_sql_comments: 'false'
        auto_quote_keyword: 'true'
        show_sql: 'false'
        default_batch_fetch_size: 10
    database-platform: org.hibernate.dialect.MySQLDialect